version: '3.8'

services:

  mysqldb:
    image: mysql:8
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Sunil@9439
      MYSQL_DATABASE: disasterdb

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - disaster-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: disaster-app
    restart: always

    depends_on:
      mysqldb:
        condition: service_healthy

    ports:
      - "8086:8086"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/disasterdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Sunil@9439

      # Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

      # Spring Security default login
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin123

    networks:
      - disaster-network

volumes:
  mysql_data:

networks:
  disaster-network:
    driver: bridge